name: Release-Notes-Preview

on:
  pull_request:
    branches: [ master, beta ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate release notes
        id: release-notes-preview
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0
      - name: Comment release notes preview
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.release-notes-preview.outputs.releaseNotes }}
